name: Docker Image CI

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:
    inputs:
      ffmpeg_branch:
        description: "FFmpeg branch"
        required: true
        default: "test/7.1.5/main"
        type: string

permissions:
  contents: read
  packages: write

env:
  FFMPEG_BRANCH: test/8.1.2/main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Get FFmpeg release
        id: ffmpeg
        run: |
          git clone \
            --branch "$FFMPEG_BRANCH" \
            --depth 1 \
            https://github.com/jc-kynesim/rpi-ffmpeg.git \
            /tmp/rpi-ffmpeg

          RELEASE=$(cat /tmp/rpi-ffmpeg/RELEASE)

          echo "FFmpeg branch:  $FFMPEG_BRANCH"
          echo "FFmpeg release: $RELEASE"

          echo "release=$RELEASE" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          RELEASE: ${{ steps.ffmpeg.outputs.release }}
        run: |
          REPO="ghcr.io/${{ github.repository }}"

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg FFMPEG_BRANCH="$FFMPEG_BRANCH" \
            -f Dockerfile \
            -t "$REPO:$RELEASE" \
            -t "$REPO:latest" \
            --push \
            .
